
# This file is automatically generated by puppet-swagger-generator and
# any manual changes are likely to be clobbered when the files
# are regenerated.

require_relative '../../../puppet_x/puppetlabs/kubernetes/provider'

Puppet::Type.type(:kubernetes_storage_class).provide(:swagger, :parent => PuppetX::Puppetlabs::Kubernetes::Provider) do

  mk_resource_methods

  def self.instance_to_hash(instance)
    {
      ensure: :present,
      name: instance_name(instance),
      allow_volume_expansion: instance.allowVolumeExpansion.respond_to?(:to_hash) ? instance.allowVolumeExpansion.to_hash : instance.allowVolumeExpansion,
      allowed_topologies: instance.allowedTopologies.respond_to?(:to_hash) ? instance.allowedTopologies.to_hash : instance.allowedTopologies,
      metadata: instance.metadata.respond_to?(:to_hash) ? instance.metadata.to_hash : instance.metadata,
      mount_options: instance.mountOptions.respond_to?(:to_hash) ? instance.mountOptions.to_hash : instance.mountOptions,
      parameters: instance.parameters.respond_to?(:to_hash) ? instance.parameters.to_hash : instance.parameters,
      provisioner: instance.provisioner.respond_to?(:to_hash) ? instance.provisioner.to_hash : instance.provisioner,
      reclaim_policy: instance.reclaimPolicy.respond_to?(:to_hash) ? instance.reclaimPolicy.to_hash : instance.reclaimPolicy,
      volume_binding_mode: instance.volumeBindingMode.respond_to?(:to_hash) ? instance.volumeBindingMode.to_hash : instance.volumeBindingMode,
      object: instance,
    }
  end

  def create
    Puppet.info("Creating kubernetes_storage_class #{name}")
    create_instance_of('storage_class', name, build_params)
  end

  def flush
   unless @property_hash.empty?
     unless resource[:ensure] == :absent
        flush_instance_of('storage_class', name, @property_hash[:object], build_params)
      end
    end
  end

  def destroy
    Puppet.info("Deleting kubernetes_storage_class #{name}")
    destroy_instance_of('storage_class', name)
    @property_hash[:ensure] = :absent
  end

  private
  def self.list_instances
    list_instances_of('storage_class')
  end

  def build_params
    params = {
      allowVolumeExpansion: resource[:allow_volume_expansion],
      allowedTopologies: resource[:allowed_topologies],
      metadata: resource[:metadata],
      mountOptions: resource[:mount_options],
      parameters: resource[:parameters],
      provisioner: resource[:provisioner],
      reclaimPolicy: resource[:reclaim_policy],
      volumeBindingMode: resource[:volume_binding_mode],
    }
    params.delete_if { |key, value| value.nil? }
    params
  end
end
