
# This file is automatically generated by puppet-swagger-generator and
# any manual changes are likely to be clobbered when the files
# are regenerated.

require_relative '../../../puppet_x/puppetlabs/kubernetes/provider'

Puppet::Type.type(:kubernetes_service_account_token_projection).provide(:swagger, :parent => PuppetX::Puppetlabs::Kubernetes::Provider) do

  mk_resource_methods

  def self.instance_to_hash(instance)
    {
    ensure: :present,
    name: instance.metadata.name,
    
      
        audience: instance.audience.respond_to?(:to_hash) ? instance.audience.to_hash : instance.audience,
      
    
      
        expiration_seconds: instance.expirationSeconds.respond_to?(:to_hash) ? instance.expirationSeconds.to_hash : instance.expirationSeconds,
      
    
      
        path: instance.path.respond_to?(:to_hash) ? instance.path.to_hash : instance.path,
      
    
    object: instance,
    }
  end

  def create
    Puppet.info("Creating kubernetes_service_account_token_projection #{name}")
    create_instance_of('service_account_token_projection', name, build_params)
  end

  def flush
   unless @property_hash.empty?
     unless resource[:ensure] == :absent
        flush_instance_of('service_account_token_projection', name, @property_hash[:object], build_params)
      end
    end
  end

  def destroy
    Puppet.info("Deleting kubernetes_service_account_token_projection #{name}")
    destroy_instance_of('service_account_token_projection', name)
    @property_hash[:ensure] = :absent
  end

  private
  def self.list_instances
    list_instances_of('service_account_token_projection')
  end

  def build_params
    params = {
    
      
        audience: resource[:audience],
      
    
      
        expirationSeconds: resource[:expiration_seconds],
      
    
      
        path: resource[:path],
      
    
    }
    params.delete_if { |key, value| value.nil? }
    params
  end
end
