
# This file is automatically generated by puppet-swagger-generator and
# any manual changes are likely to be clobbered when the files
# are regenerated.

require_relative '../../../puppet_x/puppetlabs/kubernetes/provider'

Puppet::Type.type(:kubernetes_priority_class).provide(:swagger, :parent => PuppetX::Puppetlabs::Kubernetes::Provider) do

  mk_resource_methods

  def self.instance_to_hash(instance)
    {
      ensure: :present,
      name: instance_name(instance),
      description: instance.description.respond_to?(:to_hash) ? instance.description.to_hash : instance.description,
      global_default: instance.globalDefault.respond_to?(:to_hash) ? instance.globalDefault.to_hash : instance.globalDefault,
      metadata: instance.metadata.respond_to?(:to_hash) ? instance.metadata.to_hash : instance.metadata,
      value: instance.value.respond_to?(:to_hash) ? instance.value.to_hash : instance.value,
      object: instance,
    }
  end

  def create
    Puppet.info("Creating kubernetes_priority_class #{name}")
    create_instance_of('priority_class', name, build_params)
  end

  def flush
   unless @property_hash.empty?
     unless resource[:ensure] == :absent
        flush_instance_of('priority_class', name, @property_hash[:object], build_params)
      end
    end
  end

  def destroy
    Puppet.info("Deleting kubernetes_priority_class #{name}")
    destroy_instance_of('priority_class', name)
    @property_hash[:ensure] = :absent
  end

  private
  def self.list_instances
    list_instances_of('priority_class')
  end

  def build_params
    params = {
      description: resource[:description],
      globalDefault: resource[:global_default],
      metadata: resource[:metadata],
      value: resource[:value],
    }
    params.delete_if { |key, value| value.nil? }
    params
  end
end
