
# This file is automatically generated by puppet-swagger-generator and
# any manual changes are likely to be clobbered when the files
# are regenerated.

require_relative '../../../puppet_x/puppetlabs/kubernetes/provider'

Puppet::Type.type(:kubernetes_stateful_set_status).provide(:swagger, :parent => PuppetX::Puppetlabs::Kubernetes::Provider) do

  mk_resource_methods

  def self.instance_to_hash(instance)
    {
    ensure: :present,
    name: instance.metadata.name,
    
      
      
        observed_generation: instance.observedGeneration.respond_to?(:to_hash) ? instance.observedGeneration.to_hash : instance.observedGeneration,
      
      
    
      
      
        replicas: instance.replicas.respond_to?(:to_hash) ? instance.replicas.to_hash : instance.replicas,
      
      
    
      
      
        ready_replicas: instance.readyReplicas.respond_to?(:to_hash) ? instance.readyReplicas.to_hash : instance.readyReplicas,
      
      
    
      
      
        current_replicas: instance.currentReplicas.respond_to?(:to_hash) ? instance.currentReplicas.to_hash : instance.currentReplicas,
      
      
    
      
      
        updated_replicas: instance.updatedReplicas.respond_to?(:to_hash) ? instance.updatedReplicas.to_hash : instance.updatedReplicas,
      
      
    
      
      
        current_revision: instance.currentRevision.respond_to?(:to_hash) ? instance.currentRevision.to_hash : instance.currentRevision,
      
      
    
      
      
        update_revision: instance.updateRevision.respond_to?(:to_hash) ? instance.updateRevision.to_hash : instance.updateRevision,
      
      
    
      
      
        collision_count: instance.collisionCount.respond_to?(:to_hash) ? instance.collisionCount.to_hash : instance.collisionCount,
      
      
    
      
      
        conditions: hash_arrays(conditions),
      
      
    
    object: instance,
    }
  end

  def create
    Puppet.info("Creating kubernetes_stateful_set_status #{name}")
    create_instance_of('stateful_set_status', name, build_params)
  end

  def flush
   unless @property_hash.empty?
     unless resource[:ensure] == :absent
        flush_instance_of('stateful_set_status', name, @property_hash[:object], build_params)
      end
    end
  end

  def destroy
    Puppet.info("Deleting kubernetes_stateful_set_status #{name}")
    destroy_instance_of('stateful_set_status', name)
    @property_hash[:ensure] = :absent
  end

  private
  def self.list_instances
    list_instances_of('stateful_set_status')
  end

  def build_params
    params = {
    
      
        observedGeneration: resource[:observed_generation],
      
    
      
        replicas: resource[:replicas],
      
    
      
        readyReplicas: resource[:ready_replicas],
      
    
      
        currentReplicas: resource[:current_replicas],
      
    
      
        updatedReplicas: resource[:updated_replicas],
      
    
      
        currentRevision: resource[:current_revision],
      
    
      
        updateRevision: resource[:update_revision],
      
    
      
        collisionCount: resource[:collision_count],
      
    
      
        conditions: resource[:conditions],
      
    
    }
    params.delete_if { |key, value| value.nil? }
    params
  end
end
