
# This file is automatically generated by puppet-swagger-generator and
# any manual changes are likely to be clobbered when the files
# are regenerated.

require_relative '../../puppet_x/puppetlabs/swagger/fuzzy_compare'

Puppet::Type.newtype(:kubernetes_rolling_update_stateful_set_strategy) do
  
  @doc = "RollingUpdateStatefulSetStrategy is used to communicate parameter for RollingUpdateStatefulSetStrategyType."
  

  ensurable
apply_to_all

  

  newparam(:name, namevar: true) do
    desc 'Name of the rolling_update_stateful_set_strategy.'
  end
  
    
      
      newproperty(:partition) do
      
        
        desc "Partition indicates the ordinal at which the StatefulSet should be partitioned. Default value is 0."
        
        def insync?(is)
          PuppetX::Puppetlabs::Swagger::Utils::fuzzy_compare(is, should)
        end
      end
    
  
end
