
# This file is automatically generated by puppet-swagger-generator and
# any manual changes are likely to be clobbered when the files
# are regenerated.

require_relative '../../puppet_x/puppetlabs/swagger/fuzzy_compare'
require_relative '../../puppet_x/puppetlabs/swagger/differ'

Puppet::Type.newtype(:kubernetes_cron_job) do
  
  @doc = "CronJob represents the configuration of a single cron job."
  

  ensurable
  
  apply_to_all

  
  newparam(:name, namevar: true) do
    desc 'Name of the cron_job.'
  end

  newproperty(:metadata) do
    desc "Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata"

    def insync?(is)
      PuppetX::Puppetlabs::Swagger::Utils::fuzzy_compare(is, should)
    end
    
    include PuppetX::Puppetlabs::Swagger::Differ
    def change_to_s(current_value, newvalue)
      property_diff_with_hashdiff(current_value, newvalue)
    end
    
  end

  newproperty(:spec) do
    desc "Specification of the desired behavior of a cron job, including the schedule. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#spec-and-status"

    def insync?(is)
      PuppetX::Puppetlabs::Swagger::Utils::fuzzy_compare(is, should)
    end
    
    include PuppetX::Puppetlabs::Swagger::Differ
    def change_to_s(current_value, newvalue)
      property_diff_with_hashdiff(current_value, newvalue)
    end
    
  end

  newproperty(:status) do
    desc "Current status of a cron job. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#spec-and-status"

    def insync?(is)
      PuppetX::Puppetlabs::Swagger::Utils::fuzzy_compare(is, should)
    end
    
    include PuppetX::Puppetlabs::Swagger::Differ
    def change_to_s(current_value, newvalue)
      property_diff_with_hashdiff(current_value, newvalue)
    end
    
  end

end
