
# This file is automatically generated by puppet-swagger-generator and
# any manual changes are likely to be clobbered when the files
# are regenerated.

require_relative '../../puppet_x/puppetlabs/swagger/fuzzy_compare'

Puppet::Type.newtype(:kubernetes_volume_device) do
  
  @doc = "volumeDevice describes a mapping of a raw block device within a container."
  

  ensurable
apply_to_all

  
  validate do
    required_properties = [
    
      :name,
    
      :device_path,
    
    ]
    required_properties.each do |property|
      # We check for both places so as to cover the puppet resource path as well
      if self[property].nil? and self.provider.send(property) == :absent
        fail "You must provide a #{property}"
      end
    end
  end
  

  newparam(:name, namevar: true) do
    desc 'Name of the volume_device.'
  end
  
    
      
      newproperty(:name) do
      
        
        desc "name must match the name of a persistentVolumeClaim in the pod"
        
        def insync?(is)
          PuppetX::Puppetlabs::Swagger::Utils::fuzzy_compare(is, should)
        end
      end
    
  
    
      
      newproperty(:device_path) do
      
        
        desc "devicePath is the path inside of the container that the device will be mapped to."
        
        def insync?(is)
          PuppetX::Puppetlabs::Swagger::Utils::fuzzy_compare(is, should)
        end
      end
    
  
end
