
# This file is automatically generated by puppet-swagger-generator and
# any manual changes are likely to be clobbered when the files
# are regenerated.

require_relative '../../puppet_x/puppetlabs/swagger/fuzzy_compare'
require_relative '../../puppet_x/puppetlabs/swagger/differ'

Puppet::Type.newtype(:kubernetes_validating_webhook_configuration) do
  
  @doc = "ValidatingWebhookConfiguration describes the configuration of and admission webhook that accept or reject and object without changing it."
  

  ensurable
  
  apply_to_all

  
  newparam(:name, namevar: true) do
    desc 'Name of the validating_webhook_configuration.'
  end

  newproperty(:metadata) do
    desc "Standard object metadata; More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata."

    def insync?(is)
      PuppetX::Puppetlabs::Swagger::Utils::fuzzy_compare(is, should)
    end
    
    include PuppetX::Puppetlabs::Swagger::Differ
    def change_to_s(current_value, newvalue)
      property_diff_with_hashdiff(current_value, newvalue)
    end
    
  end

  newproperty(:webhooks, :array_matching => :all) do
    desc "Webhooks is a list of webhooks and the affected resources and operations."

    def insync?(is)
      PuppetX::Puppetlabs::Swagger::Utils::fuzzy_compare(is, should)
    end
    
  end

end
