
# This file is automatically generated by puppet-swagger-generator and
# any manual changes are likely to be clobbered when the files
# are regenerated.

require_relative '../../puppet_x/puppetlabs/swagger/fuzzy_compare'

Puppet::Type.newtype(:kubernetes_pod_dns_config_option) do
  
  @doc = "PodDNSConfigOption defines DNS resolver options of a pod."
  

  ensurable
apply_to_all

  

  newparam(:name, namevar: true) do
    desc 'Name of the pod_dns_config_option.'
  end
  
    
      
      newproperty(:name) do
      
        
        desc "Required."
        
        def insync?(is)
          PuppetX::Puppetlabs::Swagger::Utils::fuzzy_compare(is, should)
        end
      end
    
  
    
      
      newproperty(:value) do
      
        
        def insync?(is)
          PuppetX::Puppetlabs::Swagger::Utils::fuzzy_compare(is, should)
        end
      end
    
  
end
