
# This file is automatically generated by puppet-swagger-generator and
# any manual changes are likely to be clobbered when the files
# are regenerated.

require_relative '../../puppet_x/puppetlabs/swagger/fuzzy_compare'

Puppet::Type.newtype(:kubernetes_pod_readiness_gate) do
  
  @doc = "PodReadinessGate contains the reference to a pod condition"
  

  ensurable

  
  validate do
    required_properties = [
    
      :condition_type,
    
    ]
    required_properties.each do |property|
      # We check for both places so as to cover the puppet resource path as well
      if self[property].nil? and self.provider.send(property) == :absent
        fail "You must provide a #{property}"
      end
    end
  end
  

  newparam(:name, namevar: true) do
    desc 'Name of the pod_readiness_gate.'
  end
  
    
      
      newproperty(:condition_type) do
      
        
        desc "ConditionType refers to a condition in the pod's condition list with matching type."
        
        def insync?(is)
          PuppetX::Puppetlabs::Swagger::Utils::fuzzy_compare(is, should)
        end
      end
    
  
end
