
# This file is automatically generated by puppet-swagger-generator and
# any manual changes are likely to be clobbered when the files
# are regenerated.

require_relative '../../puppet_x/puppetlabs/swagger/fuzzy_compare'

Puppet::Type.newtype(:kubernetes_node_selector_term) do
  
  @doc = "A null or empty node selector term matches no objects. The requirements of them are ANDed. The TopologySelectorTerm type implements a subset of the NodeSelectorTerm."
  

  ensurable

  

  newparam(:name, namevar: true) do
    desc 'Name of the node_selector_term.'
  end
  
    
      
      newproperty(:match_expressions, :array_matching => :all) do
      
        
        desc "A list of node selector requirements by node's labels."
        
        def insync?(is)
          PuppetX::Puppetlabs::Swagger::Utils::fuzzy_compare(is, should)
        end
      end
    
  
    
      
      newproperty(:match_fields, :array_matching => :all) do
      
        
        desc "A list of node selector requirements by node's fields."
        
        def insync?(is)
          PuppetX::Puppetlabs::Swagger::Utils::fuzzy_compare(is, should)
        end
      end
    
  
end
